"""Associate expenses witha  budget

Revision ID: 4872cbd5ebe8
Revises: b2014e9f7491
Create Date: 2026-04-17 16:42:28.355728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4872cbd5ebe8'
down_revision = 'b2014e9f7491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key(batch_op.f('fk_expenses_budget_id_budget'), 'budget', ['budget_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_expenses_budget_id_budget'), type_='foreignkey')
        batch_op.drop_column('budget_id')

    # ### end Alembic commands ###
